/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Fri Jun 16 17:20:42 2017. */

#ifndef PB_SS_PROTO_BACKEND_BASESTATION_BACKEND_BASESTATION_PB_H_INCLUDED
#define PB_SS_PROTO_BACKEND_BASESTATION_BACKEND_BASESTATION_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ss_proto_backend_basestation_LinkType {
    ss_proto_backend_basestation_LinkType_UNKNOWN = 0,
    ss_proto_backend_basestation_LinkType_CELLULAR = 1,
    ss_proto_backend_basestation_LinkType_WIFI = 2,
    ss_proto_backend_basestation_LinkType_ETHERNET = 3
} ss_proto_backend_basestation_LinkType;
#define _ss_proto_backend_basestation_LinkType_MIN ss_proto_backend_basestation_LinkType_UNKNOWN
#define _ss_proto_backend_basestation_LinkType_MAX ss_proto_backend_basestation_LinkType_ETHERNET
#define _ss_proto_backend_basestation_LinkType_ARRAYSIZE ((ss_proto_backend_basestation_LinkType)(ss_proto_backend_basestation_LinkType_ETHERNET+1))

typedef enum _ss_proto_backend_basestation_SensorType {
    ss_proto_backend_basestation_SensorType_KEYPAD = 1,
    ss_proto_backend_basestation_SensorType_KEYCHAIN = 2,
    ss_proto_backend_basestation_SensorType_PANIC_BUTTON = 3,
    ss_proto_backend_basestation_SensorType_MOTION = 4,
    ss_proto_backend_basestation_SensorType_ENTRY = 5,
    ss_proto_backend_basestation_SensorType_GLASSBREAK = 6,
    ss_proto_backend_basestation_SensorType_CARBON_MONOXIDE = 7,
    ss_proto_backend_basestation_SensorType_SMOKE = 8,
    ss_proto_backend_basestation_SensorType_WATER = 9,
    ss_proto_backend_basestation_SensorType_FREEZE = 10,
    ss_proto_backend_basestation_SensorType_NEST = 11,
    ss_proto_backend_basestation_SensorType_CAMERA = 12,
    ss_proto_backend_basestation_SensorType_SIREN = 13
} ss_proto_backend_basestation_SensorType;
#define _ss_proto_backend_basestation_SensorType_MIN ss_proto_backend_basestation_SensorType_KEYPAD
#define _ss_proto_backend_basestation_SensorType_MAX ss_proto_backend_basestation_SensorType_SIREN
#define _ss_proto_backend_basestation_SensorType_ARRAYSIZE ((ss_proto_backend_basestation_SensorType)(ss_proto_backend_basestation_SensorType_SIREN+1))

typedef enum _ss_proto_backend_basestation_SetupReply_Status {
    ss_proto_backend_basestation_SetupReply_Status_OK = 1,
    ss_proto_backend_basestation_SetupReply_Status_FAILED_CONNECTION = 2,
    ss_proto_backend_basestation_SetupReply_Status_FAILED_AUTHENTICATION = 3,
    ss_proto_backend_basestation_SetupReply_Status_FAILED_ALREADY_REGISTERED = 4
} ss_proto_backend_basestation_SetupReply_Status;
#define _ss_proto_backend_basestation_SetupReply_Status_MIN ss_proto_backend_basestation_SetupReply_Status_OK
#define _ss_proto_backend_basestation_SetupReply_Status_MAX ss_proto_backend_basestation_SetupReply_Status_FAILED_ALREADY_REGISTERED
#define _ss_proto_backend_basestation_SetupReply_Status_ARRAYSIZE ((ss_proto_backend_basestation_SetupReply_Status)(ss_proto_backend_basestation_SetupReply_Status_FAILED_ALREADY_REGISTERED+1))

typedef enum _ss_proto_backend_basestation_Login_Version {
    ss_proto_backend_basestation_Login_Version_V0 = 0
} ss_proto_backend_basestation_Login_Version;
#define _ss_proto_backend_basestation_Login_Version_MIN ss_proto_backend_basestation_Login_Version_V0
#define _ss_proto_backend_basestation_Login_Version_MAX ss_proto_backend_basestation_Login_Version_V0
#define _ss_proto_backend_basestation_Login_Version_ARRAYSIZE ((ss_proto_backend_basestation_Login_Version)(ss_proto_backend_basestation_Login_Version_V0+1))

typedef enum _ss_proto_backend_basestation_State_States {
    ss_proto_backend_basestation_State_States_OFF = 1,
    ss_proto_backend_basestation_State_States_HOME = 2,
    ss_proto_backend_basestation_State_States_HOME_COUNT = 3,
    ss_proto_backend_basestation_State_States_AWAY = 4,
    ss_proto_backend_basestation_State_States_AWAY_COUNT = 5,
    ss_proto_backend_basestation_State_States_HOME2 = 6,
    ss_proto_backend_basestation_State_States_HOME2_COUNT = 7,
    ss_proto_backend_basestation_State_States_AWAY2 = 8,
    ss_proto_backend_basestation_State_States_AWAY2_COUNT = 9,
    ss_proto_backend_basestation_State_States_ALARM = 10,
    ss_proto_backend_basestation_State_States_ALARM_COUNT = 11,
    ss_proto_backend_basestation_State_States_MENU = 12,
    ss_proto_backend_basestation_State_States_TEST = 13,
    ss_proto_backend_basestation_State_States_NAMING = 14,
    ss_proto_backend_basestation_State_States_INSTALL = 15,
    ss_proto_backend_basestation_State_States_UPDATE = 16,
    ss_proto_backend_basestation_State_States_DOWNLOAD_BS = 17,
    ss_proto_backend_basestation_State_States_DOWNLOAD_KP = 18,
    ss_proto_backend_basestation_State_States_DOWNLOAD_SUCCESS = 19,
    ss_proto_backend_basestation_State_States_DOWNLOAD_FAIL = 20
} ss_proto_backend_basestation_State_States;
#define _ss_proto_backend_basestation_State_States_MIN ss_proto_backend_basestation_State_States_OFF
#define _ss_proto_backend_basestation_State_States_MAX ss_proto_backend_basestation_State_States_DOWNLOAD_FAIL
#define _ss_proto_backend_basestation_State_States_ARRAYSIZE ((ss_proto_backend_basestation_State_States)(ss_proto_backend_basestation_State_States_DOWNLOAD_FAIL+1))

typedef enum _ss_proto_backend_basestation_Sensor_Operation {
    ss_proto_backend_basestation_Sensor_Operation_NOOP = 0,
    ss_proto_backend_basestation_Sensor_Operation_ADD = 1,
    ss_proto_backend_basestation_Sensor_Operation_MODIFY = 2,
    ss_proto_backend_basestation_Sensor_Operation_DELETE = 3,
    ss_proto_backend_basestation_Sensor_Operation_ERROR = 4
} ss_proto_backend_basestation_Sensor_Operation;
#define _ss_proto_backend_basestation_Sensor_Operation_MIN ss_proto_backend_basestation_Sensor_Operation_NOOP
#define _ss_proto_backend_basestation_Sensor_Operation_MAX ss_proto_backend_basestation_Sensor_Operation_ERROR
#define _ss_proto_backend_basestation_Sensor_Operation_ARRAYSIZE ((ss_proto_backend_basestation_Sensor_Operation)(ss_proto_backend_basestation_Sensor_Operation_ERROR+1))

typedef enum _ss_proto_backend_basestation_NormalSettings_Volume {
    ss_proto_backend_basestation_NormalSettings_Volume_OFF = 0,
    ss_proto_backend_basestation_NormalSettings_Volume_LOW = 1,
    ss_proto_backend_basestation_NormalSettings_Volume_MED = 2,
    ss_proto_backend_basestation_NormalSettings_Volume_HIGH = 3
} ss_proto_backend_basestation_NormalSettings_Volume;
#define _ss_proto_backend_basestation_NormalSettings_Volume_MIN ss_proto_backend_basestation_NormalSettings_Volume_OFF
#define _ss_proto_backend_basestation_NormalSettings_Volume_MAX ss_proto_backend_basestation_NormalSettings_Volume_HIGH
#define _ss_proto_backend_basestation_NormalSettings_Volume_ARRAYSIZE ((ss_proto_backend_basestation_NormalSettings_Volume)(ss_proto_backend_basestation_NormalSettings_Volume_HIGH+1))

typedef enum _ss_proto_backend_basestation_Settings_Groups {
    ss_proto_backend_basestation_Settings_Groups_NONE = 0,
    ss_proto_backend_basestation_Settings_Groups_ADMIN = 1,
    ss_proto_backend_basestation_Settings_Groups_PINS = 2,
    ss_proto_backend_basestation_Settings_Groups_SENSORS = 4,
    ss_proto_backend_basestation_Settings_Groups_NORMAL = 8,
    ss_proto_backend_basestation_Settings_Groups_RADIO = 16,
    ss_proto_backend_basestation_Settings_Groups_PERMANENT = 32,
    ss_proto_backend_basestation_Settings_Groups_ALL = 63
} ss_proto_backend_basestation_Settings_Groups;
#define _ss_proto_backend_basestation_Settings_Groups_MIN ss_proto_backend_basestation_Settings_Groups_NONE
#define _ss_proto_backend_basestation_Settings_Groups_MAX ss_proto_backend_basestation_Settings_Groups_ALL
#define _ss_proto_backend_basestation_Settings_Groups_ARRAYSIZE ((ss_proto_backend_basestation_Settings_Groups)(ss_proto_backend_basestation_Settings_Groups_ALL+1))

typedef enum _ss_proto_backend_basestation_Alarm_Code {
    ss_proto_backend_basestation_Alarm_Code_KEYPAD_PANIC = 1,
    ss_proto_backend_basestation_Alarm_Code_KEYCHAIN_PANIC = 2,
    ss_proto_backend_basestation_Alarm_Code_PANIC_BUTTON_PANIC = 3,
    ss_proto_backend_basestation_Alarm_Code_PANIC_BUTTON_RESTORED = 4,
    ss_proto_backend_basestation_Alarm_Code_PANIC_BUTTON_ERROR = 5,
    ss_proto_backend_basestation_Alarm_Code_DURESS_ALARM = 6,
    ss_proto_backend_basestation_Alarm_Code_POTENTIAL_UNAUTHORIZED_DISARM = 7,
    ss_proto_backend_basestation_Alarm_Code_MFA_CONFIRMED = 8,
    ss_proto_backend_basestation_Alarm_Code_CANCEL_ALARM_KEYCHAIN = 9,
    ss_proto_backend_basestation_Alarm_Code_CANCEL_ALARM_PIN_1 = 10,
    ss_proto_backend_basestation_Alarm_Code_CANCEL_ALARM_PIN_2 = 11,
    ss_proto_backend_basestation_Alarm_Code_CANCEL_ALARM_PIN_3 = 12,
    ss_proto_backend_basestation_Alarm_Code_CANCEL_ALARM_PIN_4 = 13,
    ss_proto_backend_basestation_Alarm_Code_CANCEL_ALARM_PIN_5 = 14,
    ss_proto_backend_basestation_Alarm_Code_ALARM_OFF_KEYCHAIN = 15,
    ss_proto_backend_basestation_Alarm_Code_ALARM_OFF_PIN_1 = 16,
    ss_proto_backend_basestation_Alarm_Code_ALARM_OFF_PIN_2 = 17,
    ss_proto_backend_basestation_Alarm_Code_ALARM_OFF_PIN_3 = 18,
    ss_proto_backend_basestation_Alarm_Code_ALARM_OFF_PIN_4 = 19,
    ss_proto_backend_basestation_Alarm_Code_ALARM_OFF_PIN_5 = 20,
    ss_proto_backend_basestation_Alarm_Code_ALARM_OFF_REMOTE = 21,
    ss_proto_backend_basestation_Alarm_Code_ALARM_OFF_GENERIC = 22,
    ss_proto_backend_basestation_Alarm_Code_ALARM_ON_HOME = 23,
    ss_proto_backend_basestation_Alarm_Code_ALARM_ON_AWAY = 24,
    ss_proto_backend_basestation_Alarm_Code_MOTION_ALARM = 25,
    ss_proto_backend_basestation_Alarm_Code_MOTION_SENSOR_RESTORED = 26,
    ss_proto_backend_basestation_Alarm_Code_MOTION_SENSOR_ERROR = 27,
    ss_proto_backend_basestation_Alarm_Code_GLASS_BREAK_ALARM = 28,
    ss_proto_backend_basestation_Alarm_Code_GLASS_BREAK_SENSOR_RESTORED = 29,
    ss_proto_backend_basestation_Alarm_Code_GLASS_BREAK_SENSOR_ERROR = 30,
    ss_proto_backend_basestation_Alarm_Code_INTERIOR_ALARM = 31,
    ss_proto_backend_basestation_Alarm_Code_ENTRY_ALARM = 32,
    ss_proto_backend_basestation_Alarm_Code_ENTRY_SENSOR_RESTORED = 33,
    ss_proto_backend_basestation_Alarm_Code_ENTRY_SENSOR_ERROR = 34,
    ss_proto_backend_basestation_Alarm_Code_RECENT_CLOSE = 35,
    ss_proto_backend_basestation_Alarm_Code_FIRE_ALARM = 36,
    ss_proto_backend_basestation_Alarm_Code_FIRE_ALARM_STOPPED = 37,
    ss_proto_backend_basestation_Alarm_Code_SMOKE_DETECTOR_RESTORED = 38,
    ss_proto_backend_basestation_Alarm_Code_SMOKE_DETECTOR_ERROR = 39,
    ss_proto_backend_basestation_Alarm_Code_SMOKE_TEST = 40,
    ss_proto_backend_basestation_Alarm_Code_FLOOD_ALARM = 41,
    ss_proto_backend_basestation_Alarm_Code_FLOOD_ALARM_STOPPED = 42,
    ss_proto_backend_basestation_Alarm_Code_WATER_SENSOR_RESTORED = 43,
    ss_proto_backend_basestation_Alarm_Code_WATER_SENSOR_ERROR = 44,
    ss_proto_backend_basestation_Alarm_Code_LOW_TEMP_ALARM = 45,
    ss_proto_backend_basestation_Alarm_Code_LOW_TEMP_ALARM_STOPPED = 46,
    ss_proto_backend_basestation_Alarm_Code_FREEZE_SENSOR_RESTORED = 47,
    ss_proto_backend_basestation_Alarm_Code_FREEZE_SENSOR_ERROR = 48,
    ss_proto_backend_basestation_Alarm_Code_CARBON_MONOXIDE_ALARM = 49,
    ss_proto_backend_basestation_Alarm_Code_CARBON_MONOXIDE_ALARM_STOPPED = 50,
    ss_proto_backend_basestation_Alarm_Code_CARBON_MONOXIDE_RESTORED = 51,
    ss_proto_backend_basestation_Alarm_Code_CARBON_MONOXIDE_ERROR = 52,
    ss_proto_backend_basestation_Alarm_Code_CARBON_MONOXIDE_TEST = 53,
    ss_proto_backend_basestation_Alarm_Code_E_NOTIFY = 54,
    ss_proto_backend_basestation_Alarm_Code_OTHER_ALARM_EVENT = 55,
    ss_proto_backend_basestation_Alarm_Code_MEDICAL_ALARM = 56,
    ss_proto_backend_basestation_Alarm_Code_USER_INITIATED_TEST = 57,
    ss_proto_backend_basestation_Alarm_Code_AUTOMATIC_TEST = 58,
    ss_proto_backend_basestation_Alarm_Code_RF_JAM = 59,
    ss_proto_backend_basestation_Alarm_Code_POWER_OUTAGE = 60,
    ss_proto_backend_basestation_Alarm_Code_POWER_RESTORED = 61,
    ss_proto_backend_basestation_Alarm_Code_BASESTATION_BATTERY_LOW = 62,
    ss_proto_backend_basestation_Alarm_Code_BASESTATION_BATTERY_RESTORED = 63,
    ss_proto_backend_basestation_Alarm_Code_WIFI_LOST = 64,
    ss_proto_backend_basestation_Alarm_Code_WIFI_RESTORED = 65,
    ss_proto_backend_basestation_Alarm_Code_BACKEND_TRIGGER = 66,
    ss_proto_backend_basestation_Alarm_Code_KEYPAD_ACTIVATED = 67,
    ss_proto_backend_basestation_Alarm_Code_KEYPAD_TEST = 68,
    ss_proto_backend_basestation_Alarm_Code_KEYCHAIN_ACTIVATED = 69,
    ss_proto_backend_basestation_Alarm_Code_KEYCHAIN_TEST = 70,
    ss_proto_backend_basestation_Alarm_Code_PANIC_BUTTON_ACTIVATED = 71,
    ss_proto_backend_basestation_Alarm_Code_PANIC_BUTTON_TEST = 72,
    ss_proto_backend_basestation_Alarm_Code_MOTION_ACTIVATED = 73,
    ss_proto_backend_basestation_Alarm_Code_MOTION_TEST = 74,
    ss_proto_backend_basestation_Alarm_Code_ENTRY_ACTIVATED = 75,
    ss_proto_backend_basestation_Alarm_Code_ENTRY_TEST = 76,
    ss_proto_backend_basestation_Alarm_Code_GLASS_BREAK_ACTIVATED = 77,
    ss_proto_backend_basestation_Alarm_Code_GLASS_BREAK_TEST = 78,
    ss_proto_backend_basestation_Alarm_Code_CARBON_MONOXIDE_ACTIVATED = 79,
    ss_proto_backend_basestation_Alarm_Code_SMOKE_ACTIVATED = 80,
    ss_proto_backend_basestation_Alarm_Code_WATER_ACTIVATED = 81,
    ss_proto_backend_basestation_Alarm_Code_WATER_TEST = 82,
    ss_proto_backend_basestation_Alarm_Code_FREEZE_ACTIVATED = 83,
    ss_proto_backend_basestation_Alarm_Code_FREEZE_TEST = 84
} ss_proto_backend_basestation_Alarm_Code;
#define _ss_proto_backend_basestation_Alarm_Code_MIN ss_proto_backend_basestation_Alarm_Code_KEYPAD_PANIC
#define _ss_proto_backend_basestation_Alarm_Code_MAX ss_proto_backend_basestation_Alarm_Code_FREEZE_TEST
#define _ss_proto_backend_basestation_Alarm_Code_ARRAYSIZE ((ss_proto_backend_basestation_Alarm_Code)(ss_proto_backend_basestation_Alarm_Code_FREEZE_TEST+1))

typedef enum _ss_proto_backend_basestation_FirmwareUpdate_Type {
    ss_proto_backend_basestation_FirmwareUpdate_Type_UPLOAD_FIRST = 1,
    ss_proto_backend_basestation_FirmwareUpdate_Type_UPLOAD_MIDDLE = 2,
    ss_proto_backend_basestation_FirmwareUpdate_Type_UPLOAD_LAST = 3,
    ss_proto_backend_basestation_FirmwareUpdate_Type_FLASHING_START = 4,
    ss_proto_backend_basestation_FirmwareUpdate_Type_QUERY = 5
} ss_proto_backend_basestation_FirmwareUpdate_Type;
#define _ss_proto_backend_basestation_FirmwareUpdate_Type_MIN ss_proto_backend_basestation_FirmwareUpdate_Type_UPLOAD_FIRST
#define _ss_proto_backend_basestation_FirmwareUpdate_Type_MAX ss_proto_backend_basestation_FirmwareUpdate_Type_QUERY
#define _ss_proto_backend_basestation_FirmwareUpdate_Type_ARRAYSIZE ((ss_proto_backend_basestation_FirmwareUpdate_Type)(ss_proto_backend_basestation_FirmwareUpdate_Type_QUERY+1))

typedef enum _ss_proto_backend_basestation_FirmwareUpdate_DataType {
    ss_proto_backend_basestation_FirmwareUpdate_DataType_UNKNOWN = 0,
    ss_proto_backend_basestation_FirmwareUpdate_DataType_BASESTATION = 1,
    ss_proto_backend_basestation_FirmwareUpdate_DataType_AUDIO = 2,
    ss_proto_backend_basestation_FirmwareUpdate_DataType_KEYPAD = 3,
    ss_proto_backend_basestation_FirmwareUpdate_DataType_WIFI = 4
} ss_proto_backend_basestation_FirmwareUpdate_DataType;
#define _ss_proto_backend_basestation_FirmwareUpdate_DataType_MIN ss_proto_backend_basestation_FirmwareUpdate_DataType_UNKNOWN
#define _ss_proto_backend_basestation_FirmwareUpdate_DataType_MAX ss_proto_backend_basestation_FirmwareUpdate_DataType_WIFI
#define _ss_proto_backend_basestation_FirmwareUpdate_DataType_ARRAYSIZE ((ss_proto_backend_basestation_FirmwareUpdate_DataType)(ss_proto_backend_basestation_FirmwareUpdate_DataType_WIFI+1))

typedef enum _ss_proto_backend_basestation_FirmwareUpdateReply_Status {
    ss_proto_backend_basestation_FirmwareUpdateReply_Status_DOWNLOAD_OK = 1,
    ss_proto_backend_basestation_FirmwareUpdateReply_Status_ERROR_IO = 2,
    ss_proto_backend_basestation_FirmwareUpdateReply_Status_ERROR_NOSPACE = 3,
    ss_proto_backend_basestation_FirmwareUpdateReply_Status_ERROR_MD5SUM = 4,
    ss_proto_backend_basestation_FirmwareUpdateReply_Status_ERROR_FORMAT = 5,
    ss_proto_backend_basestation_FirmwareUpdateReply_Status_ERROR_FLASHING = 6,
    ss_proto_backend_basestation_FirmwareUpdateReply_Status_ERROR_BADREQUEST = 7,
    ss_proto_backend_basestation_FirmwareUpdateReply_Status_QUERY = 8,
    ss_proto_backend_basestation_FirmwareUpdateReply_Status_PROGRESS = 9
} ss_proto_backend_basestation_FirmwareUpdateReply_Status;
#define _ss_proto_backend_basestation_FirmwareUpdateReply_Status_MIN ss_proto_backend_basestation_FirmwareUpdateReply_Status_DOWNLOAD_OK
#define _ss_proto_backend_basestation_FirmwareUpdateReply_Status_MAX ss_proto_backend_basestation_FirmwareUpdateReply_Status_PROGRESS
#define _ss_proto_backend_basestation_FirmwareUpdateReply_Status_ARRAYSIZE ((ss_proto_backend_basestation_FirmwareUpdateReply_Status)(ss_proto_backend_basestation_FirmwareUpdateReply_Status_PROGRESS+1))

typedef enum _ss_proto_backend_basestation_Upload_Type {
    ss_proto_backend_basestation_Upload_Type_SS_LOG_FILE = 1,
    ss_proto_backend_basestation_Upload_Type_CORE_DUMP = 2,
    ss_proto_backend_basestation_Upload_Type_WIFI_LOG = 3,
    ss_proto_backend_basestation_Upload_Type_DMESG = 4,
    ss_proto_backend_basestation_Upload_Type_PROCS = 5
} ss_proto_backend_basestation_Upload_Type;
#define _ss_proto_backend_basestation_Upload_Type_MIN ss_proto_backend_basestation_Upload_Type_SS_LOG_FILE
#define _ss_proto_backend_basestation_Upload_Type_MAX ss_proto_backend_basestation_Upload_Type_PROCS
#define _ss_proto_backend_basestation_Upload_Type_ARRAYSIZE ((ss_proto_backend_basestation_Upload_Type)(ss_proto_backend_basestation_Upload_Type_PROCS+1))

typedef enum _ss_proto_backend_basestation_UploadReply_Status {
    ss_proto_backend_basestation_UploadReply_Status_UPLOAD_OK = 1,
    ss_proto_backend_basestation_UploadReply_Status_FILE_NOT_FOUND = 2
} ss_proto_backend_basestation_UploadReply_Status;
#define _ss_proto_backend_basestation_UploadReply_Status_MIN ss_proto_backend_basestation_UploadReply_Status_UPLOAD_OK
#define _ss_proto_backend_basestation_UploadReply_Status_MAX ss_proto_backend_basestation_UploadReply_Status_FILE_NOT_FOUND
#define _ss_proto_backend_basestation_UploadReply_Status_ARRAYSIZE ((ss_proto_backend_basestation_UploadReply_Status)(ss_proto_backend_basestation_UploadReply_Status_FILE_NOT_FOUND+1))

typedef enum _ss_proto_backend_basestation_LogFileTransfer_Type {
    ss_proto_backend_basestation_LogFileTransfer_Type_FIRST_PART = 1,
    ss_proto_backend_basestation_LogFileTransfer_Type_MIDDLE_PART = 2,
    ss_proto_backend_basestation_LogFileTransfer_Type_LAST_PART = 3
} ss_proto_backend_basestation_LogFileTransfer_Type;
#define _ss_proto_backend_basestation_LogFileTransfer_Type_MIN ss_proto_backend_basestation_LogFileTransfer_Type_FIRST_PART
#define _ss_proto_backend_basestation_LogFileTransfer_Type_MAX ss_proto_backend_basestation_LogFileTransfer_Type_LAST_PART
#define _ss_proto_backend_basestation_LogFileTransfer_Type_ARRAYSIZE ((ss_proto_backend_basestation_LogFileTransfer_Type)(ss_proto_backend_basestation_LogFileTransfer_Type_LAST_PART+1))

typedef enum _ss_proto_backend_basestation_EchoReply_Status {
    ss_proto_backend_basestation_EchoReply_Status_STATUS_OK = 1,
    ss_proto_backend_basestation_EchoReply_Status_STATUS_ERROR = 2
} ss_proto_backend_basestation_EchoReply_Status;
#define _ss_proto_backend_basestation_EchoReply_Status_MIN ss_proto_backend_basestation_EchoReply_Status_STATUS_OK
#define _ss_proto_backend_basestation_EchoReply_Status_MAX ss_proto_backend_basestation_EchoReply_Status_STATUS_ERROR
#define _ss_proto_backend_basestation_EchoReply_Status_ARRAYSIZE ((ss_proto_backend_basestation_EchoReply_Status)(ss_proto_backend_basestation_EchoReply_Status_STATUS_ERROR+1))

typedef enum _ss_proto_backend_basestation_MessageToBasestation_Type {
    ss_proto_backend_basestation_MessageToBasestation_Type_KEEP_ALIVE = 1,
    ss_proto_backend_basestation_MessageToBasestation_Type_SETUP_REPLY = 2,
    ss_proto_backend_basestation_MessageToBasestation_Type_LOGIN_REPLY = 3,
    ss_proto_backend_basestation_MessageToBasestation_Type_GET_STATE = 4,
    ss_proto_backend_basestation_MessageToBasestation_Type_SET_STATE = 5,
    ss_proto_backend_basestation_MessageToBasestation_Type_GET_SETTINGS = 6,
    ss_proto_backend_basestation_MessageToBasestation_Type_SET_SETTINGS = 7,
    ss_proto_backend_basestation_MessageToBasestation_Type_ACK_ALARM = 8,
    ss_proto_backend_basestation_MessageToBasestation_Type_TRIGGER_ALARM = 9,
    ss_proto_backend_basestation_MessageToBasestation_Type_GET_CONNECTIVITY = 10,
    ss_proto_backend_basestation_MessageToBasestation_Type_FIRMWARE_UPDATE = 11,
    ss_proto_backend_basestation_MessageToBasestation_Type_UPLOAD = 12,
    ss_proto_backend_basestation_MessageToBasestation_Type_DISCONNECT = 13,
    ss_proto_backend_basestation_MessageToBasestation_Type_ECHO_REQUEST = 14,
    ss_proto_backend_basestation_MessageToBasestation_Type_GET_STATUS_REQ = 15,
    ss_proto_backend_basestation_MessageToBasestation_Type_ADD_SENSOR = 16
} ss_proto_backend_basestation_MessageToBasestation_Type;
#define _ss_proto_backend_basestation_MessageToBasestation_Type_MIN ss_proto_backend_basestation_MessageToBasestation_Type_KEEP_ALIVE
#define _ss_proto_backend_basestation_MessageToBasestation_Type_MAX ss_proto_backend_basestation_MessageToBasestation_Type_ADD_SENSOR
#define _ss_proto_backend_basestation_MessageToBasestation_Type_ARRAYSIZE ((ss_proto_backend_basestation_MessageToBasestation_Type)(ss_proto_backend_basestation_MessageToBasestation_Type_ADD_SENSOR+1))

typedef enum _ss_proto_backend_basestation_MessageToBackend_Type {
    ss_proto_backend_basestation_MessageToBackend_Type_KEEP_ALIVE_REPLY = 1,
    ss_proto_backend_basestation_MessageToBackend_Type_SETUP = 2,
    ss_proto_backend_basestation_MessageToBackend_Type_LOGIN = 3,
    ss_proto_backend_basestation_MessageToBackend_Type_GET_STATE_REPLY = 4,
    ss_proto_backend_basestation_MessageToBackend_Type_SET_STATE_REPLY = 5,
    ss_proto_backend_basestation_MessageToBackend_Type_GET_SETTINGS_REPLY = 6,
    ss_proto_backend_basestation_MessageToBackend_Type_SET_SETTINGS_REPLY = 7,
    ss_proto_backend_basestation_MessageToBackend_Type_ALARM = 8,
    ss_proto_backend_basestation_MessageToBackend_Type_GET_CONNECTIVITY_REPLY = 10,
    ss_proto_backend_basestation_MessageToBackend_Type_FIRMWARE_UPDATE_REPLY = 11,
    ss_proto_backend_basestation_MessageToBackend_Type_UPLOAD_REPLY = 12,
    ss_proto_backend_basestation_MessageToBackend_Type_LOG_FILE = 13,
    ss_proto_backend_basestation_MessageToBackend_Type_ECHO_REPLY = 14,
    ss_proto_backend_basestation_MessageToBackend_Type_ERROR = 15,
    ss_proto_backend_basestation_MessageToBackend_Type_GET_STATUS_REPLY = 16,
    ss_proto_backend_basestation_MessageToBackend_Type_STATE_CHANGE_EVENT = 17
} ss_proto_backend_basestation_MessageToBackend_Type;
#define _ss_proto_backend_basestation_MessageToBackend_Type_MIN ss_proto_backend_basestation_MessageToBackend_Type_KEEP_ALIVE_REPLY
#define _ss_proto_backend_basestation_MessageToBackend_Type_MAX ss_proto_backend_basestation_MessageToBackend_Type_STATE_CHANGE_EVENT
#define _ss_proto_backend_basestation_MessageToBackend_Type_ARRAYSIZE ((ss_proto_backend_basestation_MessageToBackend_Type)(ss_proto_backend_basestation_MessageToBackend_Type_STATE_CHANGE_EVENT+1))

typedef enum _ss_proto_backend_basestation_MessageToBackend_ErrorType {
    ss_proto_backend_basestation_MessageToBackend_ErrorType_RECEIVE = 1
} ss_proto_backend_basestation_MessageToBackend_ErrorType;
#define _ss_proto_backend_basestation_MessageToBackend_ErrorType_MIN ss_proto_backend_basestation_MessageToBackend_ErrorType_RECEIVE
#define _ss_proto_backend_basestation_MessageToBackend_ErrorType_MAX ss_proto_backend_basestation_MessageToBackend_ErrorType_RECEIVE
#define _ss_proto_backend_basestation_MessageToBackend_ErrorType_ARRAYSIZE ((ss_proto_backend_basestation_MessageToBackend_ErrorType)(ss_proto_backend_basestation_MessageToBackend_ErrorType_RECEIVE+1))

/* Struct definitions */
typedef struct _ss_proto_backend_basestation_Connectivity {
    pb_callback_t imsi;
    pb_callback_t wlRssi;
    pb_callback_t cellCarrier;
    pb_callback_t cellMode;
    pb_callback_t cellStatus;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_Connectivity) */
} ss_proto_backend_basestation_Connectivity;

typedef struct _ss_proto_backend_basestation_PermanentSettings {
    pb_callback_t serial;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_PermanentSettings) */
} ss_proto_backend_basestation_PermanentSettings;

typedef struct _ss_proto_backend_basestation_RadioSettings {
    pb_callback_t radioSettings;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_RadioSettings) */
} ss_proto_backend_basestation_RadioSettings;

typedef struct _ss_proto_backend_basestation_AddSensor {
    ss_proto_backend_basestation_SensorType type;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_AddSensor) */
} ss_proto_backend_basestation_AddSensor;

typedef struct _ss_proto_backend_basestation_AdminSettings {
    bool has_autoRearm;
    bool autoRearm;
    bool has_swingerShutdown;
    bool swingerShutdown;
    bool has_monitoring;
    bool monitoring;
    bool has_pinResettable;
    bool pinResettable;
    bool has_autoTest;
    uint32_t autoTest;
    bool has_sensorCheckin;
    uint32_t sensorCheckin;
    pb_callback_t obiwanA;
    pb_callback_t obiwanB;
    bool has_UL985;
    bool UL985;
    bool has_jamDetection;
    bool jamDetection;
    bool has_jamThreshold;
    uint32_t jamThreshold;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_AdminSettings) */
} ss_proto_backend_basestation_AdminSettings;

typedef struct _ss_proto_backend_basestation_Alarm {
    pb_callback_t imsi;
    bool has_code;
    ss_proto_backend_basestation_Alarm_Code code;
    pb_callback_t account;
    bool has_sensorType;
    ss_proto_backend_basestation_SensorType sensorType;
    pb_callback_t serial;
    pb_callback_t name;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_Alarm) */
} ss_proto_backend_basestation_Alarm;

typedef struct _ss_proto_backend_basestation_BasestationStatus {
    bool has_wifiStatus;
    uint32_t wifiStatus;
    bool has_wifiRssi;
    uint32_t wifiRssi;
    bool has_wallPower;
    uint32_t wallPower;
    bool has_backupBattery;
    uint32_t backupBattery;
    bool has_gsmStatus;
    uint32_t gsmStatus;
    bool has_gsmRssi;
    uint32_t gsmRssi;
    bool has_ethernetStatus;
    uint32_t ethernetStatus;
    pb_callback_t encryptionErrors;
    bool has_rfJamming;
    bool rfJamming;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_BasestationStatus) */
} ss_proto_backend_basestation_BasestationStatus;

typedef struct _ss_proto_backend_basestation_EchoReply {
    ss_proto_backend_basestation_EchoReply_Status status;
    bool has_number;
    int32_t number;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_EchoReply) */
} ss_proto_backend_basestation_EchoReply;

typedef struct _ss_proto_backend_basestation_EchoRequest {
    bool has_number;
    int32_t number;
    pb_callback_t data;
    bool has_replyLen;
    int32_t replyLen;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_EchoRequest) */
} ss_proto_backend_basestation_EchoRequest;

typedef struct _ss_proto_backend_basestation_FirmwareUpdate {
    ss_proto_backend_basestation_FirmwareUpdate_Type type;
    pb_callback_t filename;
    pb_callback_t md5sum;
    pb_callback_t data;
    bool has_size;
    uint32_t size;
    bool has_offset;
    uint32_t offset;
    bool has_dataType;
    ss_proto_backend_basestation_FirmwareUpdate_DataType dataType;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_FirmwareUpdate) */
} ss_proto_backend_basestation_FirmwareUpdate;

typedef struct _ss_proto_backend_basestation_FirmwareUpdateReply {
    ss_proto_backend_basestation_FirmwareUpdateReply_Status status;
    pb_callback_t imsi;
    pb_callback_t error;
    bool has_size;
    uint32_t size;
    bool has_done;
    uint32_t done;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_FirmwareUpdateReply) */
} ss_proto_backend_basestation_FirmwareUpdateReply;

typedef struct _ss_proto_backend_basestation_LogFileTransfer {
    ss_proto_backend_basestation_LogFileTransfer_Type type;
    pb_callback_t filename;
    pb_callback_t data;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_LogFileTransfer) */
} ss_proto_backend_basestation_LogFileTransfer;

typedef struct _ss_proto_backend_basestation_Login {
    pb_callback_t imsi;
    bool has_version_major;
    uint32_t version_major;
    bool has_version_minor;
    uint32_t version_minor;
    bool has_version_build;
    uint32_t version_build;
    pb_callback_t build_version;
    bool has_protocol_version;
    ss_proto_backend_basestation_Login_Version protocol_version;
    bool has_link_type;
    ss_proto_backend_basestation_LinkType link_type;
    pb_callback_t serial;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_Login) */
} ss_proto_backend_basestation_Login;

typedef struct _ss_proto_backend_basestation_LoginReply {
    bool has_status;
    bool status;
    bool has_keep_alive_interval;
    uint32_t keep_alive_interval;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_LoginReply) */
} ss_proto_backend_basestation_LoginReply;

typedef struct _ss_proto_backend_basestation_NormalSettings {
    bool has_light;
    bool light;
    bool has_doorChime;
    ss_proto_backend_basestation_NormalSettings_Volume doorChime;
    bool has_voicePrompts;
    ss_proto_backend_basestation_NormalSettings_Volume voicePrompts;
    bool has_alarmVolume;
    ss_proto_backend_basestation_NormalSettings_Volume alarmVolume;
    bool has_exitDelayHome;
    uint32_t exitDelayHome;
    bool has_exitDelayHome2;
    uint32_t exitDelayHome2;
    bool has_exitDelayAway;
    uint32_t exitDelayAway;
    bool has_exitDelayAway2;
    uint32_t exitDelayAway2;
    bool has_entryDelayHome;
    uint32_t entryDelayHome;
    bool has_entryDelayHome2;
    uint32_t entryDelayHome2;
    bool has_entryDelayAway;
    uint32_t entryDelayAway;
    bool has_entryDelayAway2;
    uint32_t entryDelayAway2;
    bool has_alarmDuration;
    uint32_t alarmDuration;
    pb_callback_t wifiSSID;
    pb_callback_t wifiPassword;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_NormalSettings) */
} ss_proto_backend_basestation_NormalSettings;

typedef struct _ss_proto_backend_basestation_Pin {
    bool has_pin;
    uint32_t pin;
    pb_callback_t name;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_Pin) */
} ss_proto_backend_basestation_Pin;

typedef struct _ss_proto_backend_basestation_Pins {
    bool has_masterPin;
    uint32_t masterPin;
    bool has_duressPin;
    uint32_t duressPin;
    pb_callback_t pins;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_Pins) */
} ss_proto_backend_basestation_Pins;

typedef struct _ss_proto_backend_basestation_Sensor {
    ss_proto_backend_basestation_SensorType type;
    pb_callback_t serial;
    pb_callback_t name;
    bool has_setting;
    uint32_t setting;
    bool has_status;
    uint32_t status;
    bool has_flags;
    uint32_t flags;
    bool has_lastRf;
    uint32_t lastRf;
    bool has_timestamp;
    uint32_t timestamp;
    bool has_rssi;
    uint32_t rssi;
    bool has_freqOffEst;
    uint32_t freqOffEst;
    bool has_SRO_ind;
    uint32_t SRO_ind;
    bool has_operation;
    ss_proto_backend_basestation_Sensor_Operation operation;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_Sensor) */
} ss_proto_backend_basestation_Sensor;

typedef struct _ss_proto_backend_basestation_SensorStatus {
    pb_callback_t serial;
    ss_proto_backend_basestation_SensorType type;
    uint32_t status;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_SensorStatus) */
} ss_proto_backend_basestation_SensorStatus;

typedef struct _ss_proto_backend_basestation_Setup {
    pb_callback_t sid;
    pb_callback_t token;
    pb_callback_t name;
    pb_callback_t build_version;
    pb_callback_t ssid;
    bool has_link_type;
    ss_proto_backend_basestation_LinkType link_type;
    pb_callback_t serial;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_Setup) */
} ss_proto_backend_basestation_Setup;

typedef struct _ss_proto_backend_basestation_SetupReply {
    bool has_status;
    ss_proto_backend_basestation_SetupReply_Status status;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_SetupReply) */
} ss_proto_backend_basestation_SetupReply;

typedef struct _ss_proto_backend_basestation_State {
    ss_proto_backend_basestation_State_States state;
    pb_callback_t imsi;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_State) */
} ss_proto_backend_basestation_State;

typedef struct _ss_proto_backend_basestation_Upload {
    ss_proto_backend_basestation_Upload_Type type;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_Upload) */
} ss_proto_backend_basestation_Upload;

typedef struct _ss_proto_backend_basestation_UploadReply {
    ss_proto_backend_basestation_UploadReply_Status status;
    pb_callback_t data;
    bool has_size;
    uint32_t size;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_UploadReply) */
} ss_proto_backend_basestation_UploadReply;

typedef struct _ss_proto_backend_basestation_GetStatusReply {
    pb_callback_t sensors;
    pb_callback_t logs;
    bool has_status;
    ss_proto_backend_basestation_BasestationStatus status;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_GetStatusReply) */
} ss_proto_backend_basestation_GetStatusReply;

typedef struct _ss_proto_backend_basestation_Settings {
    bool has_groups;
    uint32_t groups;
    pb_callback_t imsi;
    bool has_normal;
    ss_proto_backend_basestation_NormalSettings normal;
    bool has_admin;
    ss_proto_backend_basestation_AdminSettings admin;
    bool has_permanent;
    ss_proto_backend_basestation_PermanentSettings permanent;
    bool has_pins;
    ss_proto_backend_basestation_Pins pins;
    pb_callback_t logs;
    pb_callback_t sensors;
    bool has_radio;
    ss_proto_backend_basestation_RadioSettings radio;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_Settings) */
} ss_proto_backend_basestation_Settings;

typedef struct _ss_proto_backend_basestation_MessageToBackend {
    ss_proto_backend_basestation_MessageToBackend_Type type;
    bool has_setup;
    ss_proto_backend_basestation_Setup setup;
    bool has_login;
    ss_proto_backend_basestation_Login login;
    bool has_state;
    ss_proto_backend_basestation_State state;
    bool has_settings;
    ss_proto_backend_basestation_Settings settings;
    bool has_alarm;
    ss_proto_backend_basestation_Alarm alarm;
    bool has_connectivity;
    ss_proto_backend_basestation_Connectivity connectivity;
    bool has_update;
    ss_proto_backend_basestation_FirmwareUpdateReply update;
    bool has_upload;
    ss_proto_backend_basestation_UploadReply upload;
    bool has_logFileTransfer;
    ss_proto_backend_basestation_LogFileTransfer logFileTransfer;
    bool has_echo;
    ss_proto_backend_basestation_EchoReply echo;
    bool has_error;
    ss_proto_backend_basestation_MessageToBackend_ErrorType error;
    bool has_getStatusReply;
    ss_proto_backend_basestation_GetStatusReply getStatusReply;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_MessageToBackend) */
} ss_proto_backend_basestation_MessageToBackend;

typedef struct _ss_proto_backend_basestation_MessageToBasestation {
    ss_proto_backend_basestation_MessageToBasestation_Type type;
    bool has_setup;
    ss_proto_backend_basestation_SetupReply setup;
    bool has_login;
    ss_proto_backend_basestation_LoginReply login;
    bool has_state;
    ss_proto_backend_basestation_State state;
    bool has_settings;
    ss_proto_backend_basestation_Settings settings;
    bool has_alarm;
    ss_proto_backend_basestation_Alarm alarm;
    bool has_connectivity;
    ss_proto_backend_basestation_Connectivity connectivity;
    bool has_update;
    ss_proto_backend_basestation_FirmwareUpdate update;
    bool has_upload;
    ss_proto_backend_basestation_Upload upload;
    bool has_echo;
    ss_proto_backend_basestation_EchoRequest echo;
    bool has_addSensor;
    ss_proto_backend_basestation_AddSensor addSensor;
/* @@protoc_insertion_point(struct:ss_proto_backend_basestation_MessageToBasestation) */
} ss_proto_backend_basestation_MessageToBasestation;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ss_proto_backend_basestation_Setup_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, (ss_proto_backend_basestation_LinkType)0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_SetupReply_init_default {false, (ss_proto_backend_basestation_SetupReply_Status)0}
#define ss_proto_backend_basestation_Login_init_default {{{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, (ss_proto_backend_basestation_Login_Version)0, false, (ss_proto_backend_basestation_LinkType)0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_LoginReply_init_default {false, 0, false, 0}
#define ss_proto_backend_basestation_State_init_default {(ss_proto_backend_basestation_State_States)0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_BasestationStatus_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0}
#define ss_proto_backend_basestation_Sensor_init_default {(ss_proto_backend_basestation_SensorType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, (ss_proto_backend_basestation_Sensor_Operation)0}
#define ss_proto_backend_basestation_NormalSettings_init_default {false, 0, false, (ss_proto_backend_basestation_NormalSettings_Volume)0, false, (ss_proto_backend_basestation_NormalSettings_Volume)0, false, (ss_proto_backend_basestation_NormalSettings_Volume)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ss_proto_backend_basestation_AdminSettings_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define ss_proto_backend_basestation_Pin_init_default {false, 0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_Pins_init_default {false, 0, false, 0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_PermanentSettings_init_default {{{NULL}, NULL}}
#define ss_proto_backend_basestation_RadioSettings_init_default {{{NULL}, NULL}}
#define ss_proto_backend_basestation_Settings_init_default {false, 0, {{NULL}, NULL}, false, ss_proto_backend_basestation_NormalSettings_init_default, false, ss_proto_backend_basestation_AdminSettings_init_default, false, ss_proto_backend_basestation_PermanentSettings_init_default, false, ss_proto_backend_basestation_Pins_init_default, {{NULL}, NULL}, {{NULL}, NULL}, false, ss_proto_backend_basestation_RadioSettings_init_default}
#define ss_proto_backend_basestation_Alarm_init_default {{{NULL}, NULL}, false, (ss_proto_backend_basestation_Alarm_Code)0, {{NULL}, NULL}, false, (ss_proto_backend_basestation_SensorType)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ss_proto_backend_basestation_Connectivity_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ss_proto_backend_basestation_FirmwareUpdate_init_default {(ss_proto_backend_basestation_FirmwareUpdate_Type)0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, (ss_proto_backend_basestation_FirmwareUpdate_DataType)0}
#define ss_proto_backend_basestation_FirmwareUpdateReply_init_default {(ss_proto_backend_basestation_FirmwareUpdateReply_Status)0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define ss_proto_backend_basestation_Upload_init_default {(ss_proto_backend_basestation_Upload_Type)0}
#define ss_proto_backend_basestation_UploadReply_init_default {(ss_proto_backend_basestation_UploadReply_Status)0, {{NULL}, NULL}, false, 0}
#define ss_proto_backend_basestation_LogFileTransfer_init_default {(ss_proto_backend_basestation_LogFileTransfer_Type)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ss_proto_backend_basestation_EchoRequest_init_default {false, 0, {{NULL}, NULL}, false, 0}
#define ss_proto_backend_basestation_EchoReply_init_default {(ss_proto_backend_basestation_EchoReply_Status)0, false, 0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_SensorStatus_init_default {{{NULL}, NULL}, (ss_proto_backend_basestation_SensorType)0, 0}
#define ss_proto_backend_basestation_GetStatusReply_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, ss_proto_backend_basestation_BasestationStatus_init_default}
#define ss_proto_backend_basestation_AddSensor_init_default {(ss_proto_backend_basestation_SensorType)0}
#define ss_proto_backend_basestation_MessageToBasestation_init_default {(ss_proto_backend_basestation_MessageToBasestation_Type)0, false, ss_proto_backend_basestation_SetupReply_init_default, false, ss_proto_backend_basestation_LoginReply_init_default, false, ss_proto_backend_basestation_State_init_default, false, ss_proto_backend_basestation_Settings_init_default, false, ss_proto_backend_basestation_Alarm_init_default, false, ss_proto_backend_basestation_Connectivity_init_default, false, ss_proto_backend_basestation_FirmwareUpdate_init_default, false, ss_proto_backend_basestation_Upload_init_default, false, ss_proto_backend_basestation_EchoRequest_init_default, false, ss_proto_backend_basestation_AddSensor_init_default}
#define ss_proto_backend_basestation_MessageToBackend_init_default {(ss_proto_backend_basestation_MessageToBackend_Type)0, false, ss_proto_backend_basestation_Setup_init_default, false, ss_proto_backend_basestation_Login_init_default, false, ss_proto_backend_basestation_State_init_default, false, ss_proto_backend_basestation_Settings_init_default, false, ss_proto_backend_basestation_Alarm_init_default, false, ss_proto_backend_basestation_Connectivity_init_default, false, ss_proto_backend_basestation_FirmwareUpdateReply_init_default, false, ss_proto_backend_basestation_UploadReply_init_default, false, ss_proto_backend_basestation_LogFileTransfer_init_default, false, ss_proto_backend_basestation_EchoReply_init_default, false, (ss_proto_backend_basestation_MessageToBackend_ErrorType)0, false, ss_proto_backend_basestation_GetStatusReply_init_default}
#define ss_proto_backend_basestation_Setup_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, (ss_proto_backend_basestation_LinkType)0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_SetupReply_init_zero {false, (ss_proto_backend_basestation_SetupReply_Status)0}
#define ss_proto_backend_basestation_Login_init_zero {{{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, (ss_proto_backend_basestation_Login_Version)0, false, (ss_proto_backend_basestation_LinkType)0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_LoginReply_init_zero {false, 0, false, 0}
#define ss_proto_backend_basestation_State_init_zero {(ss_proto_backend_basestation_State_States)0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_BasestationStatus_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0}
#define ss_proto_backend_basestation_Sensor_init_zero {(ss_proto_backend_basestation_SensorType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, (ss_proto_backend_basestation_Sensor_Operation)0}
#define ss_proto_backend_basestation_NormalSettings_init_zero {false, 0, false, (ss_proto_backend_basestation_NormalSettings_Volume)0, false, (ss_proto_backend_basestation_NormalSettings_Volume)0, false, (ss_proto_backend_basestation_NormalSettings_Volume)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ss_proto_backend_basestation_AdminSettings_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define ss_proto_backend_basestation_Pin_init_zero {false, 0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_Pins_init_zero {false, 0, false, 0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_PermanentSettings_init_zero {{{NULL}, NULL}}
#define ss_proto_backend_basestation_RadioSettings_init_zero {{{NULL}, NULL}}
#define ss_proto_backend_basestation_Settings_init_zero {false, 0, {{NULL}, NULL}, false, ss_proto_backend_basestation_NormalSettings_init_zero, false, ss_proto_backend_basestation_AdminSettings_init_zero, false, ss_proto_backend_basestation_PermanentSettings_init_zero, false, ss_proto_backend_basestation_Pins_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, false, ss_proto_backend_basestation_RadioSettings_init_zero}
#define ss_proto_backend_basestation_Alarm_init_zero {{{NULL}, NULL}, false, (ss_proto_backend_basestation_Alarm_Code)0, {{NULL}, NULL}, false, (ss_proto_backend_basestation_SensorType)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ss_proto_backend_basestation_Connectivity_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define ss_proto_backend_basestation_FirmwareUpdate_init_zero {(ss_proto_backend_basestation_FirmwareUpdate_Type)0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, (ss_proto_backend_basestation_FirmwareUpdate_DataType)0}
#define ss_proto_backend_basestation_FirmwareUpdateReply_init_zero {(ss_proto_backend_basestation_FirmwareUpdateReply_Status)0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define ss_proto_backend_basestation_Upload_init_zero {(ss_proto_backend_basestation_Upload_Type)0}
#define ss_proto_backend_basestation_UploadReply_init_zero {(ss_proto_backend_basestation_UploadReply_Status)0, {{NULL}, NULL}, false, 0}
#define ss_proto_backend_basestation_LogFileTransfer_init_zero {(ss_proto_backend_basestation_LogFileTransfer_Type)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ss_proto_backend_basestation_EchoRequest_init_zero {false, 0, {{NULL}, NULL}, false, 0}
#define ss_proto_backend_basestation_EchoReply_init_zero {(ss_proto_backend_basestation_EchoReply_Status)0, false, 0, {{NULL}, NULL}}
#define ss_proto_backend_basestation_SensorStatus_init_zero {{{NULL}, NULL}, (ss_proto_backend_basestation_SensorType)0, 0}
#define ss_proto_backend_basestation_GetStatusReply_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, ss_proto_backend_basestation_BasestationStatus_init_zero}
#define ss_proto_backend_basestation_AddSensor_init_zero {(ss_proto_backend_basestation_SensorType)0}
#define ss_proto_backend_basestation_MessageToBasestation_init_zero {(ss_proto_backend_basestation_MessageToBasestation_Type)0, false, ss_proto_backend_basestation_SetupReply_init_zero, false, ss_proto_backend_basestation_LoginReply_init_zero, false, ss_proto_backend_basestation_State_init_zero, false, ss_proto_backend_basestation_Settings_init_zero, false, ss_proto_backend_basestation_Alarm_init_zero, false, ss_proto_backend_basestation_Connectivity_init_zero, false, ss_proto_backend_basestation_FirmwareUpdate_init_zero, false, ss_proto_backend_basestation_Upload_init_zero, false, ss_proto_backend_basestation_EchoRequest_init_zero, false, ss_proto_backend_basestation_AddSensor_init_zero}
#define ss_proto_backend_basestation_MessageToBackend_init_zero {(ss_proto_backend_basestation_MessageToBackend_Type)0, false, ss_proto_backend_basestation_Setup_init_zero, false, ss_proto_backend_basestation_Login_init_zero, false, ss_proto_backend_basestation_State_init_zero, false, ss_proto_backend_basestation_Settings_init_zero, false, ss_proto_backend_basestation_Alarm_init_zero, false, ss_proto_backend_basestation_Connectivity_init_zero, false, ss_proto_backend_basestation_FirmwareUpdateReply_init_zero, false, ss_proto_backend_basestation_UploadReply_init_zero, false, ss_proto_backend_basestation_LogFileTransfer_init_zero, false, ss_proto_backend_basestation_EchoReply_init_zero, false, (ss_proto_backend_basestation_MessageToBackend_ErrorType)0, false, ss_proto_backend_basestation_GetStatusReply_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ss_proto_backend_basestation_Connectivity_imsi_tag 1
#define ss_proto_backend_basestation_Connectivity_wlRssi_tag 2
#define ss_proto_backend_basestation_Connectivity_cellCarrier_tag 3
#define ss_proto_backend_basestation_Connectivity_cellMode_tag 4
#define ss_proto_backend_basestation_Connectivity_cellStatus_tag 5
#define ss_proto_backend_basestation_PermanentSettings_serial_tag 1
#define ss_proto_backend_basestation_RadioSettings_radioSettings_tag 1
#define ss_proto_backend_basestation_AddSensor_type_tag 1
#define ss_proto_backend_basestation_AdminSettings_autoRearm_tag 1
#define ss_proto_backend_basestation_AdminSettings_swingerShutdown_tag 2
#define ss_proto_backend_basestation_AdminSettings_monitoring_tag 3
#define ss_proto_backend_basestation_AdminSettings_pinResettable_tag 4
#define ss_proto_backend_basestation_AdminSettings_autoTest_tag 5
#define ss_proto_backend_basestation_AdminSettings_sensorCheckin_tag 6
#define ss_proto_backend_basestation_AdminSettings_obiwanA_tag 7
#define ss_proto_backend_basestation_AdminSettings_obiwanB_tag 8
#define ss_proto_backend_basestation_AdminSettings_UL985_tag 9
#define ss_proto_backend_basestation_AdminSettings_jamDetection_tag 10
#define ss_proto_backend_basestation_AdminSettings_jamThreshold_tag 11
#define ss_proto_backend_basestation_Alarm_imsi_tag 1
#define ss_proto_backend_basestation_Alarm_code_tag 2
#define ss_proto_backend_basestation_Alarm_account_tag 3
#define ss_proto_backend_basestation_Alarm_sensorType_tag 4
#define ss_proto_backend_basestation_Alarm_serial_tag 5
#define ss_proto_backend_basestation_Alarm_name_tag 6
#define ss_proto_backend_basestation_BasestationStatus_wifiStatus_tag 1
#define ss_proto_backend_basestation_BasestationStatus_wifiRssi_tag 2
#define ss_proto_backend_basestation_BasestationStatus_wallPower_tag 3
#define ss_proto_backend_basestation_BasestationStatus_backupBattery_tag 4
#define ss_proto_backend_basestation_BasestationStatus_gsmStatus_tag 5
#define ss_proto_backend_basestation_BasestationStatus_gsmRssi_tag 6
#define ss_proto_backend_basestation_BasestationStatus_ethernetStatus_tag 7
#define ss_proto_backend_basestation_BasestationStatus_encryptionErrors_tag 8
#define ss_proto_backend_basestation_BasestationStatus_rfJamming_tag 9
#define ss_proto_backend_basestation_EchoReply_status_tag 1
#define ss_proto_backend_basestation_EchoReply_number_tag 2
#define ss_proto_backend_basestation_EchoReply_data_tag 3
#define ss_proto_backend_basestation_EchoRequest_number_tag 1
#define ss_proto_backend_basestation_EchoRequest_data_tag 2
#define ss_proto_backend_basestation_EchoRequest_replyLen_tag 3
#define ss_proto_backend_basestation_FirmwareUpdate_type_tag 1
#define ss_proto_backend_basestation_FirmwareUpdate_filename_tag 2
#define ss_proto_backend_basestation_FirmwareUpdate_md5sum_tag 3
#define ss_proto_backend_basestation_FirmwareUpdate_data_tag 4
#define ss_proto_backend_basestation_FirmwareUpdate_size_tag 5
#define ss_proto_backend_basestation_FirmwareUpdate_offset_tag 6
#define ss_proto_backend_basestation_FirmwareUpdate_dataType_tag 7
#define ss_proto_backend_basestation_FirmwareUpdateReply_status_tag 1
#define ss_proto_backend_basestation_FirmwareUpdateReply_imsi_tag 2
#define ss_proto_backend_basestation_FirmwareUpdateReply_error_tag 3
#define ss_proto_backend_basestation_FirmwareUpdateReply_size_tag 4
#define ss_proto_backend_basestation_FirmwareUpdateReply_done_tag 5
#define ss_proto_backend_basestation_LogFileTransfer_type_tag 1
#define ss_proto_backend_basestation_LogFileTransfer_filename_tag 2
#define ss_proto_backend_basestation_LogFileTransfer_data_tag 3
#define ss_proto_backend_basestation_Login_imsi_tag 1
#define ss_proto_backend_basestation_Login_version_major_tag 2
#define ss_proto_backend_basestation_Login_version_minor_tag 3
#define ss_proto_backend_basestation_Login_version_build_tag 4
#define ss_proto_backend_basestation_Login_build_version_tag 5
#define ss_proto_backend_basestation_Login_protocol_version_tag 6
#define ss_proto_backend_basestation_Login_link_type_tag 7
#define ss_proto_backend_basestation_Login_serial_tag 8
#define ss_proto_backend_basestation_LoginReply_status_tag 1
#define ss_proto_backend_basestation_LoginReply_keep_alive_interval_tag 2
#define ss_proto_backend_basestation_NormalSettings_light_tag 1
#define ss_proto_backend_basestation_NormalSettings_doorChime_tag 2
#define ss_proto_backend_basestation_NormalSettings_voicePrompts_tag 3
#define ss_proto_backend_basestation_NormalSettings_alarmVolume_tag 4
#define ss_proto_backend_basestation_NormalSettings_exitDelayHome_tag 5
#define ss_proto_backend_basestation_NormalSettings_exitDelayHome2_tag 6
#define ss_proto_backend_basestation_NormalSettings_exitDelayAway_tag 7
#define ss_proto_backend_basestation_NormalSettings_exitDelayAway2_tag 8
#define ss_proto_backend_basestation_NormalSettings_entryDelayHome_tag 9
#define ss_proto_backend_basestation_NormalSettings_entryDelayHome2_tag 10
#define ss_proto_backend_basestation_NormalSettings_entryDelayAway_tag 11
#define ss_proto_backend_basestation_NormalSettings_entryDelayAway2_tag 12
#define ss_proto_backend_basestation_NormalSettings_alarmDuration_tag 13
#define ss_proto_backend_basestation_NormalSettings_wifiSSID_tag 14
#define ss_proto_backend_basestation_NormalSettings_wifiPassword_tag 15
#define ss_proto_backend_basestation_Pin_pin_tag 1
#define ss_proto_backend_basestation_Pin_name_tag 2
#define ss_proto_backend_basestation_Pins_masterPin_tag 1
#define ss_proto_backend_basestation_Pins_duressPin_tag 2
#define ss_proto_backend_basestation_Pins_pins_tag 3
#define ss_proto_backend_basestation_Sensor_type_tag 1
#define ss_proto_backend_basestation_Sensor_serial_tag 2
#define ss_proto_backend_basestation_Sensor_name_tag 3
#define ss_proto_backend_basestation_Sensor_setting_tag 4
#define ss_proto_backend_basestation_Sensor_status_tag 5
#define ss_proto_backend_basestation_Sensor_flags_tag 6
#define ss_proto_backend_basestation_Sensor_lastRf_tag 7
#define ss_proto_backend_basestation_Sensor_timestamp_tag 8
#define ss_proto_backend_basestation_Sensor_rssi_tag 9
#define ss_proto_backend_basestation_Sensor_freqOffEst_tag 10
#define ss_proto_backend_basestation_Sensor_SRO_ind_tag 11
#define ss_proto_backend_basestation_Sensor_operation_tag 12
#define ss_proto_backend_basestation_SensorStatus_serial_tag 1
#define ss_proto_backend_basestation_SensorStatus_type_tag 2
#define ss_proto_backend_basestation_SensorStatus_status_tag 3
#define ss_proto_backend_basestation_Setup_sid_tag 1
#define ss_proto_backend_basestation_Setup_token_tag 2
#define ss_proto_backend_basestation_Setup_name_tag 3
#define ss_proto_backend_basestation_Setup_build_version_tag 4
#define ss_proto_backend_basestation_Setup_ssid_tag 5
#define ss_proto_backend_basestation_Setup_link_type_tag 6
#define ss_proto_backend_basestation_Setup_serial_tag 7
#define ss_proto_backend_basestation_SetupReply_status_tag 1
#define ss_proto_backend_basestation_State_state_tag 1
#define ss_proto_backend_basestation_State_imsi_tag 2
#define ss_proto_backend_basestation_Upload_type_tag 1
#define ss_proto_backend_basestation_UploadReply_status_tag 1
#define ss_proto_backend_basestation_UploadReply_data_tag 2
#define ss_proto_backend_basestation_UploadReply_size_tag 3
#define ss_proto_backend_basestation_GetStatusReply_sensors_tag 1
#define ss_proto_backend_basestation_GetStatusReply_logs_tag 2
#define ss_proto_backend_basestation_GetStatusReply_status_tag 3
#define ss_proto_backend_basestation_Settings_groups_tag 1
#define ss_proto_backend_basestation_Settings_imsi_tag 2
#define ss_proto_backend_basestation_Settings_normal_tag 3
#define ss_proto_backend_basestation_Settings_admin_tag 4
#define ss_proto_backend_basestation_Settings_permanent_tag 5
#define ss_proto_backend_basestation_Settings_pins_tag 6
#define ss_proto_backend_basestation_Settings_logs_tag 8
#define ss_proto_backend_basestation_Settings_sensors_tag 10
#define ss_proto_backend_basestation_Settings_radio_tag 11
#define ss_proto_backend_basestation_MessageToBackend_type_tag 1
#define ss_proto_backend_basestation_MessageToBackend_setup_tag 2
#define ss_proto_backend_basestation_MessageToBackend_login_tag 3
#define ss_proto_backend_basestation_MessageToBackend_state_tag 4
#define ss_proto_backend_basestation_MessageToBackend_settings_tag 5
#define ss_proto_backend_basestation_MessageToBackend_alarm_tag 6
#define ss_proto_backend_basestation_MessageToBackend_connectivity_tag 7
#define ss_proto_backend_basestation_MessageToBackend_update_tag 8
#define ss_proto_backend_basestation_MessageToBackend_upload_tag 9
#define ss_proto_backend_basestation_MessageToBackend_logFileTransfer_tag 10
#define ss_proto_backend_basestation_MessageToBackend_echo_tag 11
#define ss_proto_backend_basestation_MessageToBackend_error_tag 12
#define ss_proto_backend_basestation_MessageToBackend_getStatusReply_tag 13
#define ss_proto_backend_basestation_MessageToBasestation_type_tag 1
#define ss_proto_backend_basestation_MessageToBasestation_setup_tag 2
#define ss_proto_backend_basestation_MessageToBasestation_login_tag 3
#define ss_proto_backend_basestation_MessageToBasestation_state_tag 4
#define ss_proto_backend_basestation_MessageToBasestation_settings_tag 5
#define ss_proto_backend_basestation_MessageToBasestation_alarm_tag 6
#define ss_proto_backend_basestation_MessageToBasestation_connectivity_tag 7
#define ss_proto_backend_basestation_MessageToBasestation_update_tag 8
#define ss_proto_backend_basestation_MessageToBasestation_upload_tag 9
#define ss_proto_backend_basestation_MessageToBasestation_echo_tag 10
#define ss_proto_backend_basestation_MessageToBasestation_addSensor_tag 11

/* Struct field encoding specification for nanopb */
extern const pb_field_t ss_proto_backend_basestation_Setup_fields[8];
extern const pb_field_t ss_proto_backend_basestation_SetupReply_fields[2];
extern const pb_field_t ss_proto_backend_basestation_Login_fields[9];
extern const pb_field_t ss_proto_backend_basestation_LoginReply_fields[3];
extern const pb_field_t ss_proto_backend_basestation_State_fields[3];
extern const pb_field_t ss_proto_backend_basestation_BasestationStatus_fields[10];
extern const pb_field_t ss_proto_backend_basestation_Sensor_fields[13];
extern const pb_field_t ss_proto_backend_basestation_NormalSettings_fields[16];
extern const pb_field_t ss_proto_backend_basestation_AdminSettings_fields[12];
extern const pb_field_t ss_proto_backend_basestation_Pin_fields[3];
extern const pb_field_t ss_proto_backend_basestation_Pins_fields[4];
extern const pb_field_t ss_proto_backend_basestation_PermanentSettings_fields[2];
extern const pb_field_t ss_proto_backend_basestation_RadioSettings_fields[2];
extern const pb_field_t ss_proto_backend_basestation_Settings_fields[10];
extern const pb_field_t ss_proto_backend_basestation_Alarm_fields[7];
extern const pb_field_t ss_proto_backend_basestation_Connectivity_fields[6];
extern const pb_field_t ss_proto_backend_basestation_FirmwareUpdate_fields[8];
extern const pb_field_t ss_proto_backend_basestation_FirmwareUpdateReply_fields[6];
extern const pb_field_t ss_proto_backend_basestation_Upload_fields[2];
extern const pb_field_t ss_proto_backend_basestation_UploadReply_fields[4];
extern const pb_field_t ss_proto_backend_basestation_LogFileTransfer_fields[4];
extern const pb_field_t ss_proto_backend_basestation_EchoRequest_fields[4];
extern const pb_field_t ss_proto_backend_basestation_EchoReply_fields[4];
extern const pb_field_t ss_proto_backend_basestation_SensorStatus_fields[4];
extern const pb_field_t ss_proto_backend_basestation_GetStatusReply_fields[4];
extern const pb_field_t ss_proto_backend_basestation_AddSensor_fields[2];
extern const pb_field_t ss_proto_backend_basestation_MessageToBasestation_fields[12];
extern const pb_field_t ss_proto_backend_basestation_MessageToBackend_fields[14];

/* Maximum encoded size of messages (where known) */
/* ss_proto_backend_basestation_Setup_size depends on runtime parameters */
#define ss_proto_backend_basestation_SetupReply_size 2
/* ss_proto_backend_basestation_Login_size depends on runtime parameters */
#define ss_proto_backend_basestation_LoginReply_size 8
/* ss_proto_backend_basestation_State_size depends on runtime parameters */
/* ss_proto_backend_basestation_BasestationStatus_size depends on runtime parameters */
/* ss_proto_backend_basestation_Sensor_size depends on runtime parameters */
/* ss_proto_backend_basestation_NormalSettings_size depends on runtime parameters */
/* ss_proto_backend_basestation_AdminSettings_size depends on runtime parameters */
/* ss_proto_backend_basestation_Pin_size depends on runtime parameters */
/* ss_proto_backend_basestation_Pins_size depends on runtime parameters */
/* ss_proto_backend_basestation_PermanentSettings_size depends on runtime parameters */
/* ss_proto_backend_basestation_RadioSettings_size depends on runtime parameters */
/* ss_proto_backend_basestation_Settings_size depends on runtime parameters */
/* ss_proto_backend_basestation_Alarm_size depends on runtime parameters */
/* ss_proto_backend_basestation_Connectivity_size depends on runtime parameters */
/* ss_proto_backend_basestation_FirmwareUpdate_size depends on runtime parameters */
/* ss_proto_backend_basestation_FirmwareUpdateReply_size depends on runtime parameters */
#define ss_proto_backend_basestation_Upload_size 2
/* ss_proto_backend_basestation_UploadReply_size depends on runtime parameters */
/* ss_proto_backend_basestation_LogFileTransfer_size depends on runtime parameters */
/* ss_proto_backend_basestation_EchoRequest_size depends on runtime parameters */
/* ss_proto_backend_basestation_EchoReply_size depends on runtime parameters */
/* ss_proto_backend_basestation_SensorStatus_size depends on runtime parameters */
/* ss_proto_backend_basestation_GetStatusReply_size depends on runtime parameters */
#define ss_proto_backend_basestation_AddSensor_size 2
#define ss_proto_backend_basestation_MessageToBasestation_size (60 + ss_proto_backend_basestation_State_size + ss_proto_backend_basestation_Settings_size + ss_proto_backend_basestation_Alarm_size + ss_proto_backend_basestation_Connectivity_size + ss_proto_backend_basestation_FirmwareUpdate_size + ss_proto_backend_basestation_EchoRequest_size)
#define ss_proto_backend_basestation_MessageToBackend_size (70 + ss_proto_backend_basestation_Setup_size + ss_proto_backend_basestation_Login_size + ss_proto_backend_basestation_State_size + ss_proto_backend_basestation_Settings_size + ss_proto_backend_basestation_Alarm_size + ss_proto_backend_basestation_Connectivity_size + ss_proto_backend_basestation_FirmwareUpdateReply_size + ss_proto_backend_basestation_UploadReply_size + ss_proto_backend_basestation_LogFileTransfer_size + ss_proto_backend_basestation_EchoReply_size + ss_proto_backend_basestation_GetStatusReply_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BACKEND_BASESTATION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
