COMPONENT_ADD_INCLUDEDIRS := port wolfssl

COMPONENT_ADD_LDFLAGS := $(COMPONENT_PATH)/lib/libwolfssl.a

COMPONENT_ADD_LINKER_DEPS := $(COMPONENT_PATH)/lib/libwolfssl.a

CFLAGS +=-DWOLFSSL_USER_SETTINGS
