#!/bin/bash
set -e
export PATH="$PATH:"/opt/microchip/xc16/v1.26/bin""
export PATH="$PATH:"/opt/microchip/mplabx/v3.40/mplab_ide/bin/""

# Parse the version.h file generated by GoCD/Rake
MAJOR=$(awk '/#define MAJOR/{ print $3 }' /mnt/ss3_fw_source/main/version.h); export MAJOR
MINOR=$(awk '/#define MINOR/{ print $3 }' /mnt/ss3_fw_source/main/version.h); export MINOR
PATCH=$(awk '/#define PATCH/{ print $3 }' /mnt/ss3_fw_source/main/version.h); export PATCH
BUILD=$(awk '/#define BUILD/{ print $3 }' /mnt/ss3_fw_source/main/version.h); export BUILD
COMMIT_HASH=$(sed -n 's/#define COMMIT_HASH 0x//p' /mnt/ss3_fw_source/main/version.h); export COMMIT_HASH

# CD To the project directory and make the project
cd /mnt/ss3_fw_source/
make clean
make

# Append the version number to the output file
rm -rf /mnt/ss3_fw_source/output
mkdir -p /mnt/ss3_fw_source/output
cp /mnt/ss3_fw_source/build/esp-at.bin /mnt/ss3_fw_source/output/esp-fw.$MAJOR.$MINOR.$PATCH.$BUILD-$COMMIT_HASH.bin
