#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := sdio_host

export ESP_AT_PROJECT_PATH := $(PWD)
export IDF_PATH ?= $(ESP_AT_PROJECT_PATH)/../../esp-idf

include $(IDF_PATH)/make/project.mk

