#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SPDX-FileCopyrightText: 2024 Espressif Systems (Shanghai) CO LTD
# SPDX-License-Identifier: Apache-2.0

import sys
import os
import datetime

sys.path.insert(0, os.path.abspath('..'))
from conf_common import *  # noqa: F401, F403 - need to make available everything from common

current_year = datetime.datetime.now().year

# General information about the project.
project = u'ESP-AT 用户指南'
copyright = u'2016 - {} 乐鑫信息科技（上海）股份有限公司'.format(current_year)

pdf_title = u'ESP-AT 用户指南'
# Final PDF filename will contains target and version
pdf_file_prefix = u'esp-at'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'zh_CN'
