#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SPDX-FileCopyrightText: 2024-2025 Espressif Systems (Shanghai) CO LTD
# SPDX-License-Identifier: Apache-2.0

import sys
import os
import datetime

sys.path.insert(0, os.path.abspath('..'))
from conf_common import *  # noqa: F401, F403 - need to make available everything from common

current_year = datetime.datetime.now().year

# General information about the project.
project = 'ESP-AT User Guide'
copyright = '2016 - {}, Espressif Systems (Shanghai) Co., Ltd.'.format(current_year)

pdf_title = 'ESP-AT User Guide'
# Final PDF filename will contains target and version
pdf_file_prefix = 'esp-at'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

html_js_files = ['js/chatbot_widget_en.js']
