.TH "esp_at_custom_ops_struct" 3 "Tue Sep 22 2020" "ESP-AT User Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_at_custom_ops_struct \- esp_at_ops_struct some custom function interacting with AT  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_at\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBstatus_callback\fP )(esp_at_status_type status)"
.br
.ti -1c
.RI "void(* \fBpre_deepsleep_callback\fP )(void)"
.br
.ti -1c
.RI "void(* \fBpre_restart_callback\fP )(void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
esp_at_ops_struct some custom function interacting with AT 
.SH "Member Data Documentation"
.PP 
.SS "void(* esp_at_custom_ops_struct::pre_deepsleep_callback) (void)"
callback before enter deep sleep 
.SS "void(* esp_at_custom_ops_struct::pre_restart_callback) (void)"
callback before restart 
.SS "void(* esp_at_custom_ops_struct::status_callback) (esp_at_status_type status)"
callback when AT status changes 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-AT User Guide from the source code\&.
