.TH "esp_at_custom_ble_ops_struct" 3 "Tue Sep 22 2020" "ESP-AT User Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_at_custom_ble_ops_struct \- \fBesp_at_custom_ble_ops_struct\fP custom ble callback for AT  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_at\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t(* \fBrecv_data\fP )(uint8_t *data, int32_t len)"
.br
.ti -1c
.RI "void(* \fBconnect_cb\fP )(void)"
.br
.ti -1c
.RI "void(* \fBdisconnect_cb\fP )(void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBesp_at_custom_ble_ops_struct\fP custom ble callback for AT 
.SH "Member Data Documentation"
.PP 
.SS "void(* esp_at_custom_ble_ops_struct::connect_cb) (void)"
callback when ble connection is built 
.SS "void(* esp_at_custom_ble_ops_struct::disconnect_cb) (void)"
callback when ble connection is disconnected 
.SS "int32_t(* esp_at_custom_ble_ops_struct::recv_data) (uint8_t *data, int32_t len)"
callback when ble received data 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-AT User Guide from the source code\&.
