.TH "esp_at_cmd_struct" 3 "Tue Sep 22 2020" "ESP-AT User Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
esp_at_cmd_struct \- \fBesp_at_cmd_struct\fP used for define at command  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <esp_at\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBat_cmdName\fP"
.br
.ti -1c
.RI "uint8_t(* \fBat_testCmd\fP )(uint8_t *cmd_name)"
.br
.ti -1c
.RI "uint8_t(* \fBat_queryCmd\fP )(uint8_t *cmd_name)"
.br
.ti -1c
.RI "uint8_t(* \fBat_setupCmd\fP )(uint8_t para_num)"
.br
.ti -1c
.RI "uint8_t(* \fBat_exeCmd\fP )(uint8_t *cmd_name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBesp_at_cmd_struct\fP used for define at command 
.SH "Member Data Documentation"
.PP 
.SS "char* esp_at_cmd_struct::at_cmdName"
at command name 
.SS "uint8_t(* esp_at_cmd_struct::at_exeCmd) (uint8_t *cmd_name)"
Execute Command function pointer 
.SS "uint8_t(* esp_at_cmd_struct::at_queryCmd) (uint8_t *cmd_name)"
Query Command function pointer 
.SS "uint8_t(* esp_at_cmd_struct::at_setupCmd) (uint8_t para_num)"
Setup Command function pointer 
.SS "uint8_t(* esp_at_cmd_struct::at_testCmd) (uint8_t *cmd_name)"
Test Command function pointer 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-AT User Guide from the source code\&.
