COMPONENT_ADD_INCLUDEDIRS := port wolfssl

WOLFSSL_LIB_PATH := $(COMPONENT_PATH)/wolfssl/lib/$(IDF_TARGET)

ifdef CONFIG_ESP_DEBUG_WOLFSSL
    COMPONENT_ADD_LDFLAGS := $(WOLFSSL_LIB_PATH)/libwolfssl_nano_debug.a
    COMPONENT_ADD_LINKER_DEPS := $(WOLFSSL_LIB_PATH)/libwolfssl_nano_debug.a
else
    COMPONENT_ADD_LDFLAGS := $(WOLFSSL_LIB_PATH)/libwolfssl_nano.a
    COMPONENT_ADD_LINKER_DEPS := $(WOLFSSL_LIB_PATH)/libwolfssl_nano.a
endif

CFLAGS +=-DWOLFSSL_USER_SETTINGS
