MKFATFS_COMPONENT_PATH := $(COMPONENT_PATH)
MKFATFS_BUILD_DIR=$(abspath $(MKFATFS_COMPONENT_PATH)/mkfatfs)

# Custom recursive make for mkfatfs sub-project
MKFATFS_MAKE = +$(MAKE) -C $(MKFATFS_COMPONENT_PATH)/src

.PHONY: mkfatfs mkfatfs-clean

mkfatfs: $(SDKCONFIG_MAKEFILE)
	$(MKFATFS_MAKE) all

mkfatfs-clean:
	$(MKFATFS_MAKE) clean

clean: $(SDKCONFIG_MAKEFILE) mkfatfs-clean

